version: "3.5"
name: "oss-open-studio-services"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - oss-open-studio-data:/data

  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    env_file:
      - ./apps/web/.env.local
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${REDIS_TOKEN}
      SRH_CONNECTION_STRING: "redis://redis:6379"

volumes:
  oss-open-studio-data:
